### ISSUE TITLE
Add Domain in Blacklist

### ISSUE THREAD

**Issue by ChrisFrance** [desbma/referer-spam-domains-blacklist#4]
Hello :)
Thanks for your good work !
My 2 percent

site : 
copyrightclaims.org
redirect to :
http://ilovevitaly.com/

View in Google analytics

Thank you :)

**Comment by desbma** [comment]
Hello,

I appreciate your contribution, but both [copyrightclaims.org](https://github.com/desbma/referer-spam-domains-blacklist/blob/9234828e3c198aa3ef06043b2735ae13947d7500/spammers.txt#L272) and [ilovevitaly.com](https://github.com/desbma/referer-spam-domains-blacklist/blob/9234828e3c198aa3ef06043b2735ae13947d7500/spammers.txt#L624) are already in the list.
