### ISSUE TITLE
Is it the right place to add new sites to block?

### ISSUE THREAD

**Issue by simbus82** [desbma/referer-spam-domains-blacklist#7]
arendovalka.xyz
begalka.xyz
biteg.xyz
bezlimitko.xyz
advokateg.xyz
alfabot.xyz
abcdefh.xyz
secret.ɢoogle.com

i hope i can help!

**Comment by desbma** [comment]
Thanks for the domains.

To add them to the list, I need to know how you collected them (to avoid false positive).

Thanks

**Comment by jensholm** [comment]
Thanks for your list. I found these domains spamming my analytics. Collected them by viewing my referrals in Google Analytics for a specific site.

abc.xyz
buketeg.xyz
compliance-don.xyz
compliance-barak.xyz
compliance-george.xyz
site-speed-check.online
site-speed-checker.online
website-speed-checker.site
boltalko.xyz

**Comment by desbma** [comment]
@simbus82 I have added your domains the the list. Some were already in the list.

@jensholm I have also added your domains the the list. Some were already in the list, and some were not active so I have not added these ones.

Thank you to both of you for the contribution
