### ISSUE TITLE
Nginx & CSF

### ISSUE THREAD

**Issue by kapasite** [desbma/referer-spam-domains-blacklist#8]
How can I adapt it for Nginx & CSF?

**Comment by desbma** [comment]
Nginx + Fail2ban should be easy :
* Fail2ban already watches Nginx logs with it's default install, so maybe start by duplicating the  [`nginx-botsearch` filter](https://github.com/fail2ban/fail2ban/blob/0.10/config/jail.conf#L347)
* Either [adapt the generated failregex](https://github.com/desbma/referer-spam-domains-blacklist/blob/06fe992f811ae6e3b72c4209a0eba2d342679c47/update-fail2ban-referer-filter#L48) to your current log format, or configure Nginx to log in the [combined format](http://publib.boulder.ibm.com/tividd/td/ITWSA/ITWSA_info45/en_US/HTML/guide/c-logs.html#combined). I don't know much about Nginx, that may be what it does by default already.

Don't know about CSF though, sorry.

**Comment by kapasite** [comment]
Thank you for interest.

Example log format:

`46.105.100.149 - - [01/Jul/2017:03:38:18 +0300] "GET / HTTP/1.0" 403 564 "http://latex.xblog.in" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"`

This is referrer spammer domain.

**Comment by desbma** [comment]
Yup, it is the combined log format, so you don't need to touch the regex.

**Comment by kapasite** [comment]
Thanks.

I edited script and conf for me.

[nginx-referer]
enabled = true
maxretry = 1
bantime = 7776000
port = http,https
filter = nginx-referer
logpath = /home/nginx/domains/*/log/access.log
          /usr/local/nginx/logs/*access*.log
action = csfdeny[name=nginx-referer]

**Comment by kapasite** [comment]
Work it 👍 CSF bans...

```
2017-07-02 20:25:44,562 fail2ban.filter         [14882]: INFO    [nginx-referer] Found 54.242.96.83 - 2017-07-02 20:25:43
2017-07-02 20:25:44,662 fail2ban.actions        [14882]: NOTICE  [nginx-referer] Ban 54.242.96.83
```

/etc/fail2ban/action.d/csfdeny.conf:

```
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = csf -d <ip> Added by Fail2Ban for <name>
actionunban = csf -dr <ip>
[Init]
name = default

```
/etc/csf/csf.deny:
`54.242.96.83 # Added by Fail2Ban for nginx-referer - Sun Jul  2 20:25:44 2017`
